USE MYBDB;

SELECT * FROM TB_USER 
LEFT JOIN  TB_USER_FAMILY ON TB_USER.ID = TB_USER_FAMILY.ID_USER
LEFT JOIN  TB_USER_EMPLOYMENT ON TB_USER.ID = TB_USER_EMPLOYMENT.ID_USER;


UPDATE TB_USER_FAMILY SET CIVIL_STATUS = 'S' WHERE ID_USER = 1

 